version: '3.8'

volumes:
  mysql_data:
      driver: local

services:
  mysql:
      image: 'mysql:latest'
      container_name: 'mysql-db'
      volumes:
        - mysql_data:/var/lib/mysql
      # ports:
      #   - 3306:3306
      # expose:
      #   - 3306
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: keycloak
        MYSQL_USER: keycloak
        MYSQL_PASSWORD: Password12!
  keycloak:
      image: quay.io/keycloak/keycloak:latest
      environment:
        DB_VENDOR: MYSQL
        DB_ADDR: mysql
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: Password12!
        KEYCLOAK_USER: root
        KEYCLOAK_PASSWORD: Password12!
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the MySQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "connectTimeout=30000"
      ports:
        - 8080:8080
      depends_on:
        - mysql