version: '3.8'

services:
  mariadb:
    image: mariadb
    container_name: keycloak_mariadb
    volumes:
      - mariadb_data:/var/lib/mariadb
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: core
      MYSQL_USER: admin
      MYSQL_PASSWORD: Password12!
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '--silent']
    
  adminer:
    image: adminer
    ports:
      - 8081:8080
    environment:
      ADMINER_DEFAULT_DB_DRIVER: mysql
      ADMINER_DEFAULT_DB_HOST: mariadb
      ADMINER_DEFAULT_DB_SERVER: mariadb
      ADMINER_DEFAULT_DB_NAME: core
      ADMINER_DESIGN: dracula
      ADMINER_PLUGINS: tables-filter tinymce
    expose:
      - 8081
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
      