version: '3.8'

services:
  mysql-db:
    container_name: 'mysql-db'
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    volumes:
      - mysql-db-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: 'core'
      MYSQL_USER: 'guest'
      MYSQL_PASSWORD: 'guest'
      MYSQL_PORT: 3306

  mysql-db-adminer:
    container_name: 'mysql-db-adminer'
    image: adminer
    ports:
      - 8081:8080 # check http://localhost:8081/ for mysql management ui
    expose:
      - 8081
    environment:
      ADMINER_DEFAULT_SERVER: mysql-db
      ADMINER_DEFAULT_DB_DRIVER: mysql
      ADMINER_DEFAULT_DB_HOST: mysql-db
      ADMINER_DEFAULT_DB_SERVER: mysql-db
      ADMINER_DEFAULT_DB_NAME: core
      ADMINER_DESIGN: dracula
      ADMINER_PLUGINS: tables-filter tinymce

volumes:
  mysql-db-data:
