version: '3.8'
services:
  maildev:
    image: maildev/maildev:2.0.0-beta3
    ports:
      - 1080:1080
      - 1025:1025
    environment:
      MAILDEV_WEB_USER: admin
      MAILDEV_WEB_PASS: password
      MAILDEV_INCOMING_USER: maildev
      MAILDEV_INCOMING_PASS: password
      MAILDEV_WEB_PORT: 1080
      MAILDEV_SMTP_PORT: 1025
    volumes:
      - mail-maildev-data:/var/lib/maildev

volumes:
  mail-maildev-data:
