version: '3.8'

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: adminer
      POSTGRES_DB: adminer
      POSTGRES_USER: adminer

  adminer:
    image: adminer
    ports:
      - 8081:8080
    environment:
      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DEFAULT_DB_HOST: postgres
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DEFAULT_DB_NAME: adminer
      ADMINER_DESIGN: dracula
      ADMINER_PLUGINS: tables-filter tinymce
    expose:
      - 8081
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
