version: '3.8'
services:
  api:
    container_name: 'api'
    build: .
    restart: 'always'
    ports:
      - 3000:3000
    # cpu_count: 2
    # cpus: '0.25'
    # mem_limit: 2048MB
    # env_file: .env
    volumes:
      - api_data:/var/lib/api
    environment:
      NODE_ENV: development
      APP_PORT: 3000

volumes:
  api_data:
    driver: local