version: '3.8'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: core
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Password12!
